function(putils_get_runtime_output_directories dst_list)
	set(${dst_list}
		${CMAKE_RUNTIME_OUTPUT_DIRECTORY}
		${CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG}
		${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE}
		${CMAKE_RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL}
		${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO}
		PARENT_SCOPE
	)
endfunction()
