
#ifndef PUTILS_PLUGIN_MANAGER_EXPORT_H
#define PUTILS_PLUGIN_MANAGER_EXPORT_H

#ifdef PUTILS_PLUGIN_MANAGER_STATIC_DEFINE
#  define PUTILS_PLUGIN_MANAGER_EXPORT
#  define PUTILS_PLUGIN_MANAGER_NO_EXPORT
#else
#  ifndef PUTILS_PLUGIN_MANAGER_EXPORT
#    ifdef putils_plugin_manager_EXPORTS
        /* We are building this library */
#      define PUTILS_PLUGIN_MANAGER_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define PUTILS_PLUGIN_MANAGER_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef PUTILS_PLUGIN_MANAGER_NO_EXPORT
#    define PUTILS_PLUGIN_MANAGER_NO_EXPORT 
#  endif
#endif

#ifndef PUTILS_PLUGIN_MANAGER_DEPRECATED
#  define PUTILS_PLUGIN_MANAGER_DEPRECATED __declspec(deprecated)
#endif

#ifndef PUTILS_PLUGIN_MANAGER_DEPRECATED_EXPORT
#  define PUTILS_PLUGIN_MANAGER_DEPRECATED_EXPORT PUTILS_PLUGIN_MANAGER_EXPORT PUTILS_PLUGIN_MANAGER_DEPRECATED
#endif

#ifndef PUTILS_PLUGIN_MANAGER_DEPRECATED_NO_EXPORT
#  define PUTILS_PLUGIN_MANAGER_DEPRECATED_NO_EXPORT PUTILS_PLUGIN_MANAGER_NO_EXPORT PUTILS_PLUGIN_MANAGER_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef PUTILS_PLUGIN_MANAGER_NO_DEPRECATED
#    define PUTILS_PLUGIN_MANAGER_NO_DEPRECATED
#  endif
#endif

#endif /* PUTILS_PLUGIN_MANAGER_EXPORT_H */
